pub mod agent_detector;
pub mod agent_resume;
pub mod browser_service;
pub mod file_watch_service;
pub mod filesystem_service;
pub mod process_util;
pub mod project_service;
pub mod repository_intelligence;
pub mod repository_service;
pub mod restoration_scheduler;
pub mod startup_service;
pub mod swarm_service;
pub mod task_title;
pub mod terminal_manager;
pub mod update_service;
pub mod usage_service;
pub mod window_chrome;
pub mod window_registry;

pub use agent_detector::AgentDetector;
pub use agent_resume::AgentResumeService;
pub use browser_service::BrowserService;
pub use file_watch_service::FileWatchService;
pub use filesystem_service::{FileSystemService, SelfWriteLedger};
pub use project_service::ProjectService;
pub use repository_service::RepositoryService;
pub use restoration_scheduler::RestorationScheduler;
pub use swarm_service::SwarmService;
pub use terminal_manager::TerminalManager;
pub use update_service::UpdateService;
pub use usage_service::UsageService;
pub use window_registry::{detached_label, WindowRegistry, MAIN_WINDOW_LABEL};
