/* eslint-disable react-hooks/exhaustive-deps */
import { useCallback, useEffect, useState } from 'react'
import { open } from '@tauri-apps/plugin-dialog'
import { Navigate, useLocation, useNavigate, useParams } from 'react-router-dom'
import { AlertTriangle, ArrowLeft, Bot, Check, ChevronDown, CircleDashed, FileCheck2, FolderSearch, GitBranch, MoreHorizontal, PanelRightClose, PanelRightOpen, Play, Plus, RefreshCw, Search, Workflow } from 'lucide-react'
import { Brand } from '../components/ui/Brand'
import { Button } from '../components/ui/Button'
import { ErrorNotice } from '../components/ui/ErrorNotice'
import { TextPromptDialog } from '../components/ui/TextPromptDialog'
import { MissionComposer } from '../features/mission-control/components/MissionCreationDialog'
import { ReviewCenter } from '../features/mission-control/components/ReviewCenter'
import { TaskEditorDialog } from '../features/mission-control/components/TaskEditorDialog'
import { missionMatchesFilter, missionProgress, needsAttention } from '../features/mission-control/missionSelectors'
import { useMissionStore, useMissionUiStore, type MissionFilter, type MissionTab } from '../features/mission-control/missionStore'
import type { EvidenceRecord, Mission, MissionBundle, MissionTask, SaveMissionRequest } from '../features/mission-control/missionTypes'
import { native } from '../native/commands'
import type { ProjectOverview } from '../native/types'

const labels:Record<string,string>={draft:'Draft',planning:'Planning',ready:'Ready',running:'Running',blocked:'Blocked',verifying:'Verifying',review:'Needs Review',completed:'Completed',failed:'Failed',cancelled:'Cancelled',archived:'Archived',pending:'Pending',starting:'Starting','waiting-for-input':'Input needed',passed:'Passed'}
const tabs:MissionTab[]=['overview','plan','execution','verification','review','evidence','activity']
const filters:Array<{id:MissionFilter;label:string}>=[{id:'all',label:'All'},{id:'draft',label:'Draft'},{id:'active',label:'Active'},{id:'review',label:'Needs Review'},{id:'blocked',label:'Blocked'},{id:'completed',label:'Completed'},{id:'archived',label:'Archived'}]
function requestOf(b:MissionBundle,status=b.mission.status):SaveMissionRequest{return{id:b.mission.id,projectId:b.mission.projectId,originWorkspaceId:b.mission.originWorkspaceId,title:b.mission.title,objective:b.mission.objective,constraints:b.mission.constraints,referencePaths:b.mission.referencePaths,preferredAgentIds:b.mission.preferredAgentIds,status,executionMode:b.mission.executionMode,riskLevel:b.mission.riskLevel,permissionProfile:b.mission.permissionProfile,verificationProfileId:b.mission.verificationProfileId,acceptanceCriteria:b.acceptanceCriteria.map((c)=>({id:c.id,description:c.description,required:c.required}))}}
function routeState(l:ReturnType<typeof useLocation>){return(l.state??{})as{from?:string;originWorkspaceId?:string}}

export function LegacyMissionControlRedirect(){const[target,setTarget]=useState<string>();const[failed,setFailed]=useState(false);useEffect(()=>{void native.listProjectsOverview().then((items)=>{const last=[...items].sort((a,b)=>b.project.lastOpenedAt.localeCompare(a.project.lastOpenedAt))[0];if(last)setTarget('/project/'+last.project.id+'/missions');else setFailed(true)}).catch(()=>setFailed(true))},[]);if(target)return<Navigate to={target} replace/>;if(failed)return<Navigate to="/" replace state={{notice:'Choose a project before opening Mission Control.'}}/>;return<div className="route-loading"><span/><span/><span/></div>}

export function MissionComposerRoute(){
 const{projectId}=useParams<{projectId:string}>();const navigate=useNavigate();const location=useLocation();const state=routeState(location);const store=useMissionStore();const[overview,setOverview]=useState<ProjectOverview>();const[initialDraft,setInitialDraft]=useState<MissionBundle|null>();
 useEffect(()=>{if(!projectId)return;let active=true;setOverview(undefined);setInitialDraft(undefined);void native.listProjectsOverview().then(async(items)=>{const match=items.find((item)=>item.project.id===projectId);if(!match){navigate('/',{replace:true,state:{notice:'Choose a valid project before opening Mission Control.'}});return}useMissionStore.setState({projectId});const draft=await native.getProjectMissionDraft(projectId);if(!active)return;setOverview(match);setInitialDraft(draft);void store.bootstrapProject(projectId,!match.folderMissing).catch(()=>undefined)}).catch(()=>{if(active)navigate('/',{replace:true,state:{notice:'ForgeMind could not load this Project Mission Draft.'}})});return()=>{active=false}},[projectId,navigate,store.bootstrapProject])
 if(!projectId)return<Navigate to="/" replace/>;if(!overview||initialDraft===undefined)return<div className="route-loading"><span/><span/><span/></div>;
 const originWorkspaceId=overview.workspaces.some((workspace)=>workspace.id===state.originWorkspaceId)?state.originWorkspaceId:undefined
 return<MissionComposer overview={overview} agents={store.agents} profiles={store.verificationProfiles} originWorkspaceId={originWorkspaceId} initialDraft={initialDraft??undefined} onCancel={()=>navigate(state.from??('/project/'+projectId+'/missions'))} onSaveDraft={(request)=>store.saveMission(request)} onCreatePlan={async(request)=>{const bundle=await store.saveMission(request);navigate('/project/'+projectId+'/missions/'+bundle.mission.id,{replace:true,state:{from:state.from}});if(bundle.mission.executionMode==='assisted-plan')void store.suggestAndCreateTasks().catch(()=>undefined);return bundle}}/>
}

export function MissionControl(){
 const{projectId,missionId,taskId}=useParams<{projectId:string;missionId?:string;taskId?:string}>();const navigate=useNavigate();const location=useLocation();const origin=routeState(location).from??'/';const store=useMissionStore();const ui=useMissionUiStore()
 const[projects,setProjects]=useState<ProjectOverview[]>([]);const[query,setQuery]=useState('');const[menu,setMenu]=useState<string>();const[rename,setRename]=useState<Mission>();const[taskEditor,setTaskEditor]=useState<{task?:MissionTask}|null>(null);const[changesTask,setChangesTask]=useState<MissionTask>();const[manualEvidence,setManualEvidence]=useState<{taskId:string;criterionId:string}>()
 const loadProjects=useCallback(async()=>setProjects(await native.listProjectsOverview()),[])
 useEffect(()=>{if(!projectId)return;void Promise.all([loadProjects(),store.load(projectId,missionId)]).then(([,valid])=>{if(missionId&&!valid)navigate('/project/'+projectId+'/missions',{replace:true,state:{from:origin}})})},[projectId,missionId,origin,navigate,loadProjects,store.load])
 const overview=projects.find((p)=>p.project.id===projectId)
 useEffect(()=>{if(projectId&&overview){void store.bootstrapProject(projectId,!overview.folderMissing).catch(()=>undefined);void store.reconcile().catch(()=>undefined)}},[projectId,overview?.folderMissing,store.bootstrapProject,store.reconcile])
 useEffect(()=>{if(taskId)ui.setSelectedTask(taskId)},[taskId,ui.setSelectedTask])
 const liveTaskKey=store.bundle?.tasks.filter((t)=>['pending','starting','running','waiting-for-input'].includes(t.status)).map((t)=>t.id).join('|')??''
 useEffect(()=>{if(!projectId||!liveTaskKey)return;const timer=window.setInterval(()=>{const ids=liveTaskKey.split('|').filter(Boolean);void Promise.all(ids.map((id)=>native.refreshMissionTask(projectId,id))).then(()=>store.refresh()).catch(()=>undefined)},2500);return()=>window.clearInterval(timer)},[projectId,liveTaskKey,store.refresh])
 if(!projectId)return<Navigate to="/" replace state={{notice:'Choose a project before opening Mission Control.'}}/>
 if(projects.length&&!overview)return<Navigate to="/" replace state={{notice:'Choose a valid project before opening Mission Control.'}}/>
 const project=overview?.project,b=store.bundle,missing=overview?.folderMissing??false,task=b?.tasks.find((t)=>t.id===ui.selectedTaskId),evidence=b?.evidence.find((e)=>e.id===ui.selectedEvidenceId),profile=store.verificationProfiles.find((p)=>p.id===(task?.verificationProfileId??b?.mission.verificationProfileId)),filtered=store.missions.filter((m)=>missionMatchesFilter(m,ui.filter)&&(m.title+' '+m.objective).toLowerCase().includes(query.toLowerCase()))
 const selectMission=(id:string)=>{ui.setSelectedTask();ui.setSelectedEvidence();ui.setTab('overview');navigate('/project/'+projectId+'/missions/'+id,{state:{from:origin}})}
 const selectTask=(t:MissionTask)=>{ui.setSelectedTask(t.id);navigate('/project/'+projectId+'/missions/'+b?.mission.id+'/tasks/'+t.id,{replace:true,state:{from:origin}})}
 const create=()=>navigate('/project/'+projectId+'/missions/new',{state:{from:origin,originWorkspaceId:routeState(location).originWorkspaceId}})
 const update=async(m:Mission,status:Mission['status'],title=m.title)=>{const source=b?.mission.id===m.id?b:await native.getMissionBundle(projectId,m.id);await store.saveMission({...requestOf(source,status),title})}
 const duplicate=async(m:Mission)=>{const source=await native.getMissionBundle(projectId,m.id);const copy=await store.saveMission({...requestOf(source,'draft'),id:undefined,title:m.title+' copy',acceptanceCriteria:source.acceptanceCriteria.map((c)=>({description:c.description,required:c.required}))});selectMission(copy.mission.id)}
 const locate=async()=>{if(!project)return;const path=await open({directory:true,multiple:false,title:'Locate '+project.name});if(path&&!Array.isArray(path)){await native.relocateProject(project.id,path);await loadProjects()}}
 const approveProfile=async()=>{if(!profile||!projectId)return;await native.saveVerificationProfile({id:profile.id,projectId,name:profile.name,checks:profile.checks,approved:true});await store.bootstrapProject(projectId,false)}
 return<main className="project-missions-shell"><header className="project-missions-topbar"><Button variant="ghost" icon={<ArrowLeft size={16}/>} onClick={()=>navigate(origin)}/><Brand compact/><div className="project-missions-context"><strong>{project?.name??'Loading Project'}</strong>{project?.gitBranch&&<span><GitBranch size={12}/>{project.gitBranch}</span>}</div><label className="project-missions-switcher">Project<select value={projectId} onChange={(e)=>navigate('/project/'+e.target.value+'/missions',{state:{from:origin}})}>{projects.map((p)=><option key={p.project.id} value={p.project.id}>{p.project.name}</option>)}</select><ChevronDown size={13}/></label><div className="project-missions-top-actions"><Button variant="ghost" icon={<RefreshCw size={14}/>} onClick={()=>void store.load(projectId,missionId)}>Refresh</Button><Button variant="primary" icon={<Plus size={15}/>} onClick={create}>New Mission</Button></div></header>
 {missing&&<div className="mission-folder-warning"><AlertTriangle size={15}/><span>Project folder unavailable. Mission history, Evidence, and Review remain available. Execution and worktree actions are blocked.</span><Button variant="ghost" icon={<FolderSearch size={14}/>} onClick={()=>void locate()}>Locate Project Folder</Button></div>}{store.error&&<div className="mission-global-error"><ErrorNotice message={store.error} onRetry={store.clearError}/></div>}
 <div className={'project-missions-layout '+(b&&ui.inspectorOpen?'with-inspector':'')}><aside className="project-mission-list"><header><div><h2>Missions</h2><span>{store.missions.length} in {project?.name}</span></div><div className="mission-list-actions"><Button variant="ghost" icon={<RefreshCw size={13}/>} aria-label="Refresh Missions" onClick={()=>void store.load(projectId,missionId)}/><Button variant="ghost" icon={<Plus size={14}/>} aria-label="Create Mission" onClick={create}/></div></header><label className="mission-search"><Search size={14}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search Missions"/></label><div className="mission-filter-row">{filters.map((f)=><button key={f.id} className={ui.filter===f.id?'active':''} onClick={()=>ui.setFilter(f.id)}>{f.label}</button>)}</div><div className="project-mission-rows">{filtered.map((m)=>{const s=store.summaries[m.id];return<article key={m.id} className={b?.mission.id===m.id?'selected':''}><button className="project-mission-open" onClick={()=>selectMission(m.id)}><div><strong>{m.title||'Untitled Mission'}</strong>{s?.warningCount?<AlertTriangle size={13}/>:null}</div><span className={'mission-status '+m.status}>{labels[m.status]}</span><div className="mission-row-meta"><span>{s?.passedTaskCount??0}/{s?.taskCount??0} Tasks</span><span><Bot size={11}/>{s?.activeAgentCount??0}</span>{m.riskLevel!=='low'&&<span>{m.riskLevel} risk</span>}<time>{new Date(m.updatedAt).toLocaleDateString()}</time></div></button><Button className="mission-row-menu" variant="ghost" icon={<MoreHorizontal size={15}/>} onClick={()=>setMenu(menu===m.id?undefined:m.id)}/>{menu===m.id&&<div className="context-popover mission-actions"><button onClick={()=>selectMission(m.id)}>Open</button><button onClick={()=>setRename(m)}>Rename</button><button onClick={()=>void duplicate(m)}>Duplicate</button><button disabled={['running','verifying','archived'].includes(m.status)} onClick={()=>void update(m,'archived')}>Archive</button><button disabled={!['draft','planning','ready','running','blocked','verifying','review'].includes(m.status)} onClick={()=>void update(m,'cancelled')}>Cancel</button>{m.status==='draft'&&<button className="danger-item" onClick={()=>void store.deleteDraft(m.id)}>Delete Draft</button>}</div>}</article>})}</div></aside>
 <section className="project-mission-workspace">{!store.loading&&!store.missions.length?<Empty overview={overview} onCreate={create}/>:!b?<div className="project-mission-unselected"><Workflow size={25}/><h1>Select a Mission</h1><p>Open a Mission from this Project to view its Plan, execution, Evidence, and Review state.</p></div>:<><header className="mission-workspace-header"><div><span className={'mission-status '+b.mission.status}>{labels[b.mission.status]}</span><h1>{b.mission.title}</h1><p>{b.mission.objective}</p></div><Button variant="ghost" icon={ui.inspectorOpen?<PanelRightClose size={15}/>:<PanelRightOpen size={15}/>} onClick={()=>ui.setInspectorOpen(!ui.inspectorOpen)}>{ui.inspectorOpen?'Hide Inspector':'Show Inspector'}</Button></header><nav className="mission-tabs">{tabs.map((t)=><button key={t} className={ui.tab===t?'active':''} onClick={()=>ui.setTab(t)}>{t==='review'?'Review':t[0].toUpperCase()+t.slice(1)}</button>)}</nav><TabView tab={ui.tab} b={b} task={task} profile={profile} missing={missing} onTask={selectTask} onEdit={(t)=>setTaskEditor({task:t})} onAdd={()=>setTaskEditor({})} onSave={()=>void store.saveMission(requestOf(b,'ready'))} onSuggest={()=>void store.suggestAndCreateTasks()} onDispatch={(t)=>void store.dispatch(t.id,!project?.isGitRepository)} onStop={(t)=>void store.stop(t.id)} onRecover={(id,action)=>void store.recover(id,action)} onApprove={()=>void approveProfile()} onVerify={(t,id)=>void store.verify(t.id,id)} onReview={(t)=>void store.collectEvidence(t.id).then(()=>store.openReview(t.id))} onEvidence={(e)=>ui.setSelectedEvidence(e.id)} onManualEvidence={(t,criterionId)=>setManualEvidence({taskId:t.id,criterionId})}/></>}</section>
 {b&&ui.inspectorOpen&&<Inspector project={project?.name??''} b={b} task={task} evidence={evidence} profile={profile?.name} onClose={()=>ui.setInspectorOpen(false)}/>}</div>
 {taskEditor&&b&&<TaskEditorDialog missionId={b.mission.id} task={taskEditor.task} tasks={b.tasks} criteria={b.acceptanceCriteria} agents={store.agents} profiles={store.verificationProfiles} onSave={store.saveTask} onClose={()=>setTaskEditor(null)}/>}
 {store.review&&<ReviewCenter review={store.review} busy={Boolean(store.busyAction)} projectUnavailable={missing} onClose={()=>useMissionStore.setState({review:undefined})} onAccept={()=>void store.accept(store.review!.task.id)} onChanges={()=>setChangesTask(store.review!.task)} onRetry={()=>void store.retry(store.review!.task.id)} onVerify={()=>void store.verify(store.review!.task.id)} onMerge={()=>void store.merge(store.review!.task.id)} onDiscard={()=>void store.discard(store.review!.task.id)} onCleanup={()=>void store.cleanup(store.review!.task.id)} onRollback={()=>void store.rollback(store.review!.task.id)}/>}
 {rename&&<TextPromptDialog title="Rename Mission" label="Mission title" initialValue={rename.title} confirmLabel="Rename" onClose={()=>setRename(undefined)} onConfirm={(value)=>{void update(rename,rename.status,value.trim());setRename(undefined)}}/>}
 {changesTask&&<TextPromptDialog title="Request Changes" label="Instructions for the next attempt" confirmLabel="Request Changes" onClose={()=>setChangesTask(undefined)} onConfirm={(value)=>{void store.requestChanges(changesTask.id,value);setChangesTask(undefined);useMissionStore.setState({review:undefined})}}/>}
 {manualEvidence&&<TextPromptDialog title="Add Manual Evidence" label="Describe the proof you reviewed" confirmLabel="Record Passing Evidence" onClose={()=>setManualEvidence(undefined)} onConfirm={(value)=>{void store.addManualEvidence(manualEvidence.taskId,manualEvidence.criterionId,value,true);setManualEvidence(undefined)}}/>}</main>
}

function Empty({overview,onCreate}:{overview?:ProjectOverview;onCreate:()=>void}){return<div className="project-missions-empty"><Workflow size={25}/><h1>No missions in {overview?.project.name}</h1><p>Create a mission to plan, execute, verify, and review a development objective for this project.</p><Button variant="primary" icon={<Plus size={15}/>} onClick={onCreate}>Create Mission</Button><dl><div><dt>Branch</dt><dd>{overview?.project.gitBranch??'Not available'}</dd></div><div><dt>Framework</dt><dd>{overview?.project.detectedFramework??'Not detected'}</dd></div><div><dt>Workspaces</dt><dd>{overview?.workspaces.length??0}</dd></div></dl></div>}
type RecoveryAction='retry'|'mark-failed'|'reattach'|'clean-up'
type ViewProps={tab:MissionTab;b:MissionBundle;task?:MissionTask;profile?:{id:string;name:string;approved:boolean;checks:Array<{id:string;name:string;command:string;required:boolean}>};missing:boolean;onTask:(t:MissionTask)=>void;onEdit:(t:MissionTask)=>void;onAdd:()=>void;onSave:()=>void;onSuggest:()=>void;onDispatch:(t:MissionTask)=>void;onStop:(t:MissionTask)=>void;onRecover:(id:string,action:RecoveryAction)=>void;onApprove:()=>void;onVerify:(t:MissionTask,id?:string)=>void;onReview:(t:MissionTask)=>void;onEvidence:(e:EvidenceRecord)=>void;onManualEvidence:(t:MissionTask,criterionId:string)=>void}
function TabView(p:ViewProps){const b=p.b;if(p.tab==='overview')return<div className="mission-overview-tab"><section className="mission-overview-metrics"><div><span>Acceptance</span><strong>{b.acceptanceCriteria.filter((c)=>c.status==='passed').length}/{b.acceptanceCriteria.length}</strong></div><div><span>Task progress</span><strong>{missionProgress(b.tasks)}%</strong></div><div><span>Active agents</span><strong>{b.sessions.filter((s)=>s.status==='running').length}</strong></div><div><span>Blockers</span><strong>{b.tasks.filter(needsAttention).length}</strong></div></section><section className="mission-next-action"><span>Next meaningful action</span><h2>{!b.tasks.length?'Create the execution Plan':b.tasks.some((t)=>t.status==='ready')?'Dispatch a ready Task':b.tasks.some(needsAttention)?'Resolve blocked Task work':b.tasks.some((t)=>t.status==='review')?'Review completed Task work':'Continue execution and verification'}</h2></section><div className="mission-overview-columns"><section><h2>Acceptance criteria</h2>{b.acceptanceCriteria.map((c)=><article key={c.id} className={c.status}>{c.status==='passed'?<Check size={14}/>:<CircleDashed size={14}/>}<span>{c.description}</span></article>)}</section><section><h2>Active Tasks</h2>{b.tasks.map((t)=><button key={t.id} onClick={()=>p.onTask(t)}><strong>{t.title}</strong><span className={'task-status '+t.status}>{labels[t.status]}</span></button>)}</section></div></div>
 if(p.tab==='plan')return<div className="mission-plan-tab"><header><div><h2>Execution Plan</h2><p>Tasks, dependencies, acceptance criteria, risk, permissions, and agent assignments.</p></div><div>{b.mission.executionMode==='assisted-plan'&&!b.tasks.length&&<Button onClick={p.onSuggest}>Suggest Plan</Button>}<Button icon={<Plus size={14}/>} onClick={p.onAdd}>Add Task</Button>{b.mission.status==='planning'&&b.tasks.length>0&&<Button variant="primary" onClick={p.onSave}>Mark Ready</Button>}</div></header><div className="mission-task-table">{b.tasks.map((t,i)=><button key={t.id} onClick={()=>p.onTask(t)}><span>{i+1}</span><div><strong>{t.title}</strong><p>{t.description}</p><small>{t.dependencyIds.length} dependencies | {t.acceptanceCriterionIds.length} criteria</small></div><span>{t.role??'Unassigned'}</span><span className={'task-status '+t.status}>{labels[t.status]}</span><Button variant="ghost" onClick={(e)=>{e.stopPropagation();p.onEdit(t)}}>Edit</Button></button>)}</div></div>
 if(p.tab==='execution')return<div className="execution-task-list">{b.tasks.map((t)=>{const s=b.sessions.find((x)=>x.id===t.sessionId),w=b.worktrees.find((x)=>x.id===t.worktreeId),recovery=b.recovery.find((r)=>r.taskId===t.id&&r.status==='needs-recovery');return<article key={t.id}><button onClick={()=>p.onTask(t)}><strong>{t.title}</strong><span className={'task-status '+t.status}>{labels[t.status]}</span></button><dl><div><dt>Agent Session</dt><dd>{s?.status??'Not started'}</dd></div><div><dt>Heartbeat</dt><dd>{s?.lastHeartbeatAt??'None'}</dd></div><div><dt>Worktree</dt><dd>{w?.branchName??'Not created'}</dd></div><div><dt>Recovery</dt><dd>{recovery?.reason??'Clear'}</dd></div></dl><div className="mission-task-actions">{['ready','failed','blocked','review'].includes(t.status)&&<Button variant="primary" icon={<Play size={13}/>} disabled={p.missing||!t.agentId} onClick={()=>p.onDispatch(t)}>Dispatch</Button>}{['pending','starting','running','waiting-for-input'].includes(t.status)&&<Button variant="danger" disabled={Boolean(!s)} onClick={()=>p.onStop(t)}>Stop</Button>}{recovery?.availableActions.filter((action):action is RecoveryAction=>['retry','mark-failed','reattach','clean-up'].includes(action)).map((action)=><Button key={action} disabled={p.missing&&action!=='mark-failed'} onClick={()=>p.onRecover(recovery.id,action)}>{action==='mark-failed'?'Mark Failed':action==='clean-up'?'Clean Up':action[0].toUpperCase()+action.slice(1)}</Button>)}</div></article>})}</div>
 if(p.tab==='verification'){const t=p.task??b.tasks[0];return<div className="verification-check-list">{t&&p.profile?<><header><div><h2>{p.profile.name}</h2>{!p.profile.approved&&<p>Review and approve this Project command profile before running checks.</p>}</div><div>{!p.profile.approved&&<Button disabled={p.missing} onClick={p.onApprove}>Approve Profile</Button>}<Button variant="primary" disabled={p.missing||!p.profile.approved} onClick={()=>p.onVerify(t)}>Run All Checks</Button></div></header>{p.profile.checks.map((c)=>{const r=b.verificationResults.filter((x)=>x.taskId===t.id&&x.checkId===c.id).at(-1);return<article key={c.id}><span>{r?.status==='passed'?<Check size={14}/>:<CircleDashed size={14}/>}</span><div><strong>{c.name}</strong><code>{c.command}</code>{r?.outputExcerpt&&<pre>{r.outputExcerpt}</pre>}</div><Button disabled={p.missing||!p.profile!.approved} onClick={()=>p.onVerify(t,c.id)}>Run</Button></article>})}</>:<p>Select a Task with a verification profile.</p>}</div>}
 if(p.tab==='review')return<div className="mission-review-tab"><header><h2>Review Center</h2><p>Changed files, protected files, dependency changes, migrations, environment names, warnings, merge, discard, and rollback.</p></header>{b.tasks.filter((t)=>t.worktreeId||t.status==='review').map((t)=><article key={t.id}><strong>{t.title}</strong><span>{b.evidence.filter((e)=>e.taskId===t.id).length} Evidence items</span><Button variant="primary" icon={<FileCheck2 size={14}/>} onClick={()=>p.onReview(t)}>Open Review</Button></article>)}</div>
  if(p.tab==='evidence'){const t=p.task??b.tasks[0];return<div className="mission-evidence-tab">{t&&<header><div><h2>Evidence Ledger</h2><p>Record reviewed proof against an acceptance criterion or inspect collected commands, tests, builds, and logs.</p></div><div className="mission-evidence-actions">{b.acceptanceCriteria.map((criterion)=><Button key={criterion.id} onClick={()=>p.onManualEvidence(t,criterion.id)}>Add Proof: {criterion.description}</Button>)}</div></header>}<div className="evidence-table">{b.evidence.map((e)=><button key={e.id} onClick={()=>p.onEvidence(e)}><span className={e.status}>{e.status}</span><span><strong>{e.title}</strong><small>{e.evidenceType}</small></span><code>{e.command??e.sourcePath??'ForgeMind record'}</code><span>{b.acceptanceCriteria.find((c)=>c.id===e.acceptanceCriterionId)?.description??'Mission evidence'}</span><time>{new Date(e.createdAt).toLocaleString()}</time></button>)}</div></div>}
 return<div className="mission-activity-tab">{[...b.events,...b.auditEvents].map((e)=><article key={e.id}><time>{new Date(e.createdAt).toLocaleString()}</time><div><strong>{'title'in e?e.title:e.action}</strong><p>{e.detail}</p></div></article>)}</div>}
function Inspector({project,b,task,evidence,profile,onClose}:{project:string;b:MissionBundle;task?:MissionTask;evidence?:EvidenceRecord;profile?:string;onClose:()=>void}){return<aside className="mission-context-inspector"><header><div><span>{evidence?'Evidence':task?'Task':'Mission'} Inspector</span><h2>{evidence?.title??task?.title??b.mission.title}</h2></div><Button variant="ghost" icon={<PanelRightClose size={15}/>} onClick={onClose}/></header><div className="mission-inspector-scroll"><dl><div><dt>Project</dt><dd>{project}</dd></div><div><dt>Status</dt><dd>{evidence?.status??labels[task?.status??b.mission.status]}</dd></div><div><dt>Risk</dt><dd>{b.mission.riskLevel}</dd></div><div><dt>Permission</dt><dd>{b.mission.permissionProfile}</dd></div><div><dt>Verification</dt><dd>{profile??'Not selected'}</dd></div><div><dt>Dependencies</dt><dd>{task?.dependencyIds.length??0}</dd></div><div><dt>Criteria</dt><dd>{task?.acceptanceCriterionIds.length??b.acceptanceCriteria.length}</dd></div><div><dt>Evidence</dt><dd>{task?b.evidence.filter((e)=>e.taskId===task.id).length:b.evidence.length}</dd></div></dl><p>{evidence?.summary??task?.description??b.mission.objective}</p></div></aside>}
