import type { AgentProfile } from '../../native/types'

export type MissionStatus = 'draft'|'planning'|'ready'|'running'|'blocked'|'verifying'|'review'|'completed'|'failed'|'cancelled'|'archived'
export type TaskStatus = 'pending'|'ready'|'starting'|'running'|'waiting-for-input'|'blocked'|'verifying'|'review'|'passed'|'failed'|'cancelled'

export interface AcceptanceCriterion { id:string; missionId:string; description:string; required:boolean; status:'pending'|'passed'|'failed'|'unverified'; evidenceIds:string[] }
export interface Mission { id:string; projectId:string; originWorkspaceId?:string|null; title:string; objective:string; constraints:string[]; referencePaths:string[]; preferredAgentIds:string[]; status:MissionStatus; executionMode:'manual-plan'|'assisted-plan'; riskLevel:'low'|'medium'|'high'; permissionProfile:string; verificationProfileId?:string|null; createdAt:string; updatedAt:string }
export interface MissionTask { id:string; missionId:string; title:string; description:string; agentId?:string; role?:string; status:TaskStatus; dependencyIds:string[]; acceptanceCriterionIds:string[]; workingDirectory?:string; worktreeId?:string; sessionId?:string; verificationProfileId?:string; priority:number; attempt:number; executionLock?:string; startedAt?:string; completedAt?:string; createdAt:string; updatedAt:string }
export interface WorktreeRecord { id:string; missionId:string; taskId:string; repositoryPath:string; worktreePath:string; branchName:string; baseRef:string; baseBranch?:string; status:string; ownerMarkerPath:string; restoreRef?:string; mergeCommit?:string; createdAt:string; updatedAt:string }
export interface PersistedAgentSession { id:string; missionId:string; taskId:string; agentId:string; terminalSessionId?:string; workspaceId?:string; paneId?:string; worktreeId?:string; workingDirectory:string; command:string; processId?:number; externalSessionId?:string; transcriptPath?:string; status:string; startedAt:string; lastHeartbeatAt?:string; recoveryMetadata:Record<string,unknown> }
export interface TaskEvent { id:string; missionId:string; taskId?:string; eventType:string; title:string; detail:string; status:string; metadata:Record<string,unknown>; createdAt:string }
export interface VerificationCheckDefinition { id:string; name:string; command:string; required:boolean; timeoutMs:number; workingDirectory?:string; continueOnFailure:boolean }
export interface VerificationProfile { id:string; projectId:string; name:string; checks:VerificationCheckDefinition[]; approved:boolean; createdAt:string; updatedAt:string }
export interface VerificationResult { id:string; taskId:string; checkId:string; status:'pending'|'running'|'passed'|'failed'|'timed-out'|'cancelled'; exitCode?:number; startedAt?:string; completedAt?:string; durationMs?:number; outputExcerpt?:string; artifactIds:string[] }
export interface EvidenceRecord { id:string; missionId:string; taskId?:string; acceptanceCriterionId?:string; evidenceType:string; title:string; summary:string; status:'informational'|'passed'|'failed'|'warning'; sourcePath?:string; command?:string; artifactPath?:string; metadata:Record<string,unknown>; createdAt:string }
export interface AuditEvent { id:string; missionId?:string; taskId?:string; action:string; status:string; detail:string; metadata:Record<string,unknown>; createdAt:string }
export interface RecoveryState { id:string; missionId:string; taskId?:string; sessionId?:string; status:string; reason:string; availableActions:string[]; metadata:Record<string,unknown>; createdAt:string; updatedAt:string }
export interface ProjectContext { projectId:string; architectureSummary?:string; technologyStack:string[]; importantPaths:string[]; conventions:string[]; buildCommands:string[]; testCommands:string[]; userInstructions:string[]; updatedAt:string }
export interface MissionBundle { mission:Mission; acceptanceCriteria:AcceptanceCriterion[]; tasks:MissionTask[]; worktrees:WorktreeRecord[]; sessions:PersistedAgentSession[]; events:TaskEvent[]; verificationResults:VerificationResult[]; evidence:EvidenceRecord[]; auditEvents:AuditEvent[]; recovery:RecoveryState[] }

export interface SaveMissionRequest { id?:string; projectId:string; originWorkspaceId?:string|null; title:string; objective:string; constraints:string[]; referencePaths:string[]; preferredAgentIds:string[]; status?:MissionStatus; executionMode:'manual-plan'|'assisted-plan'; riskLevel:'low'|'medium'|'high'; permissionProfile:string; verificationProfileId?:string|null; acceptanceCriteria:Array<{id?:string;description:string;required:boolean}> }
export interface SaveTaskRequest { id?:string; missionId:string; title:string; description:string; agentId?:string; role?:string; dependencyIds:string[]; acceptanceCriterionIds:string[]; verificationProfileId?:string; priority:number }
export interface DispatchResult { task:MissionTask; worktree?:WorktreeRecord; session:PersistedAgentSession; terminalSessionId?:string; warning?:string }
export interface MissionPlanSuggestion { title:string; description:string; role:string; dependencyIndexes:number[]; acceptanceCriterionIds:string[]; priority:number }
export interface FileDiff { path:string; diff:string }
export interface ReviewSnapshot { task:MissionTask; worktree?:WorktreeRecord; changedFiles:string[]; fileDiffs:FileDiff[]; unifiedDiff:string; commits:string[]; verificationResults:VerificationResult[]; evidence:EvidenceRecord[]; warnings:string[]; dependencyChanges:string[]; migrationFiles:string[]; environmentVariableNames:string[]; conflicts:string[]; criterionCoverage:AcceptanceCriterion[]; mergeEligible:boolean; mergeBlockers:string[] }
export interface ProjectContextDiscovery { context:ProjectContext; suggestedVerificationProfile:VerificationProfile; instructionFiles:string[] }
export interface MissionBootstrap { agents:AgentProfile[]; profiles:VerificationProfile[] }
