import { useState } from 'react'
import { Button } from '../../../components/ui/Button'
import { Modal } from '../../../components/ui/Modal'
import type { AgentProfile } from '../../../native/types'
import type { AcceptanceCriterion, MissionTask, SaveTaskRequest, VerificationProfile } from '../missionTypes'

const roles=['Architect','Backend','Frontend','QA','Security reviewer','General implementation']
export function TaskEditorDialog({missionId,task,tasks,criteria,agents,profiles,onSave,onClose}:{missionId:string;task?:MissionTask;tasks:MissionTask[];criteria:AcceptanceCriterion[];agents:AgentProfile[];profiles:VerificationProfile[];onSave:(request:SaveTaskRequest)=>Promise<void>;onClose:()=>void}){
  const [title,setTitle]=useState(task?.title??'');const [description,setDescription]=useState(task?.description??'');const [role,setRole]=useState(task?.role??'General implementation');const [agentId,setAgentId]=useState(task?.agentId??'');const [priority,setPriority]=useState(task?.priority??tasks.length);const [dependencies,setDependencies]=useState(task?.dependencyIds??[]);const [criterionIds,setCriterionIds]=useState(task?.acceptanceCriterionIds??[]);const [profileId,setProfileId]=useState(task?.verificationProfileId??'');const [saving,setSaving]=useState(false)
  const save=async()=>{if(!title.trim()||!description.trim())return;setSaving(true);try{await onSave({id:task?.id,missionId,title,description,agentId:agentId||undefined,role,dependencyIds:dependencies,acceptanceCriterionIds:criterionIds,verificationProfileId:profileId||undefined,priority});onClose()}finally{setSaving(false)}}
  return <Modal title={task?'Edit mission task':'Add mission task'} onClose={onClose}><form className="mission-form" onSubmit={(event)=>{event.preventDefault();void save()}}><label>Task title<input data-autofocus value={title} onChange={(event)=>setTitle(event.target.value)} required/></label><label>Description<textarea rows={5} value={description} onChange={(event)=>setDescription(event.target.value)} required/></label><div className="mission-form-grid"><label>Role<select value={role} onChange={(event)=>setRole(event.target.value)}>{roles.map((value)=><option key={value}>{value}</option>)}</select></label><label>Assigned agent<select value={agentId} onChange={(event)=>setAgentId(event.target.value)}><option value="">Unassigned</option>{agents.filter((agent)=>agent.available).map((agent)=><option key={agent.id} value={agent.id}>{agent.name}</option>)}</select></label></div><div className="mission-form-grid"><label>Plan order<input type="number" min={0} value={priority} onChange={(event)=>setPriority(Number(event.target.value))}/></label><label>Verification profile<select value={profileId} onChange={(event)=>setProfileId(event.target.value)}><option value="">Use mission profile</option>{profiles.map((profile)=><option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label></div><fieldset><legend>Dependencies</legend><div className="task-choice-grid">{tasks.filter((candidate)=>candidate.id!==task?.id).map((candidate)=><label className="check-label" key={candidate.id}><input type="checkbox" checked={dependencies.includes(candidate.id)} onChange={(event)=>setDependencies((items)=>event.target.checked?[...items,candidate.id]:items.filter((id)=>id!==candidate.id))}/>{candidate.title}</label>)}</div></fieldset><fieldset><legend>Acceptance coverage</legend><div className="task-choice-grid">{criteria.map((criterion)=><label className="check-label" key={criterion.id}><input type="checkbox" checked={criterionIds.includes(criterion.id)} onChange={(event)=>setCriterionIds((items)=>event.target.checked?[...items,criterion.id]:items.filter((id)=>id!==criterion.id))}/>{criterion.description}</label>)}</div></fieldset><footer className="mission-form-actions"><span>Cycles and missing dependencies are rejected by the domain service.</span><Button variant="ghost" onClick={onClose}>Cancel</Button><Button variant="primary" type="submit" disabled={saving||!title.trim()||!description.trim()}>{saving?'Saving…':'Save task'}</Button></footer></form></Modal>}
