import { Product } from '@/types';

export const products: Product[] = [
  {
    id: 'paralith',
    slug: 'paralith',
    name: 'Paralith',
    tagline: 'Development, coordinated.',
    category: 'Agentic Developer Environment',
    status: 'Early Access',
    isFlagship: true,
    shortDescription:
      'A next-generation agentic development environment designed to coordinate workspaces, terminals, intelligent agents, project memory, and software verification from one focused canvas.',
    fullDescription:
      'Paralith brings projects, workspaces, persistent terminal sessions, intelligent AI agents, deep project memory, code review, and continuous verification into a single unified environment engineered for serious software delivery.',
    targetAudience: [
      'Senior Software Engineers',
      'Full-Stack & Systems Architects',
      'AI & Agentic Systems Developers',
      'Technical Leads & Engineering Teams',
    ],
    capabilities: [
      {
        title: 'Multi-Agent Workspace Orchestration',
        description:
          'Spawn and coordinate specialized autonomous agents that research codebases, propose structural edits, run test suites, and execute terminal commands in parallel without blocking main workflows.',
        highlight: 'Parallel Execution',
      },
      {
        title: 'Persistent Project Memory Index',
        description:
          'Maintain real-time structural graphs of your code syntax, AST, Git commit lineage, and past decision logs so agents act with full historical context.',
        highlight: 'Zero Context Loss',
      },
      {
        title: 'Unified Integrated Terminal Engine',
        description:
          'Interact directly with native PTY terminals integrated into agent workflows with full permission controls, command auditing, and background process monitoring.',
        highlight: 'Native Shell Control',
      },
      {
        title: 'Empirical Verification & Traceability',
        description:
          'Every code edit generated by an agent must pass mandatory automated build checks, linter runs, and unit verification before landing in your branch.',
        highlight: 'Verified Code Output',
      },
      {
        title: 'Multi-Window & Multi-Display Canvas',
        description:
          'Detach agents, logs, active terminals, and visual previews across multiple monitors with zero latency or layout thrashing.',
        highlight: 'Workstation Optimized',
      },
      {
        title: 'Local-First Data Isolation',
        description:
          'Your codebase, local git history, and environment secrets remain stored locally on your machine with strict outbound proxy controls.',
        highlight: 'Air-Gapped Ready',
      },
    ],
    platforms: ['Windows', 'macOS', 'Linux'],
    downloads: [
      {
        platform: 'Windows',
        version: 'v0.9.4-preview',
        architecture: 'x64 (64-bit)',
        fileSize: '118 MB',
        releaseDate: '2026-07-15',
        checksumSha256: '9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e',
        minOsVersion: 'Windows 10 / Windows 11 (22H2+)',
        available: true,
        releaseNotesUrl: '/products/paralith#release-notes',
      },
      {
        platform: 'macOS',
        version: 'v0.9.4-preview',
        architecture: 'Apple Silicon (M1/M2/M3/M4) & Intel',
        fileSize: '124 MB',
        releaseDate: '2026-07-15',
        checksumSha256: 'a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0',
        minOsVersion: 'macOS 13.0 (Ventura) or later',
        available: true,
        releaseNotesUrl: '/products/paralith#release-notes',
      },
      {
        platform: 'Linux',
        version: 'v0.9.4-preview',
        architecture: 'x86_64 (.AppImage / .deb)',
        fileSize: '112 MB',
        releaseDate: '2026-07-15',
        checksumSha256: 'f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9',
        minOsVersion: 'Ubuntu 22.04 LTS / Fedora 38+',
        available: true,
        releaseNotesUrl: '/products/paralith#release-notes',
      },
    ],
    heroVisualType: 'paralith-system',
    primaryCtaText: 'Download Paralith Preview',
    secondaryCtaText: 'Request Early Access',
    faqs: [
      {
        question: 'Is Paralith an AI code editor or a complete IDE platform?',
        answer:
          'Paralith is a multi-agent development environment built from the ground up to handle complex, multi-file software engineering tasks rather than simple line-by-line autocompletion. It coordinates workspaces, terminal shells, memory indices, and verification runs.',
      },
      {
        question: 'Does Paralith send my source code to public LLM training datasets?',
        answer:
          'No. Paralith follows strict local-first privacy principles. Code telemetry is completely disabled by default, and project memory indices are stored locally on your device.',
      },
      {
        question: 'Can I use Paralith with custom local models or private LLM endpoints?',
        answer:
          'Yes. Paralith supports local inference via Ollama/vLLM as well as private enterprise cloud endpoints with custom API credentials.',
      },
      {
        question: 'What platforms are currently supported?',
        answer:
          'Paralith builds native desktop distributions for Windows 11/10 (x64), macOS (Universal Binary for Apple Silicon and Intel), and Linux (AppImage & deb).',
      },
    ],
  },
];
