import { Product } from '@/types';

export const products: Product[] = [
  {
    id: 'paralith',
    slug: 'paralith',
    name: 'Paralith',
    tagline: 'Development, coordinated.',
    category: 'Agentic Developer Environment',
    status: 'Early Access',
    isFlagship: true,
    shortDescription:
      'A next-generation agentic development environment designed to coordinate workspaces, terminals, intelligent agents, project memory, and software verification from one focused canvas.',
    fullDescription:
      'Paralith brings projects, workspaces, persistent terminal sessions, intelligent AI agents, deep project memory, code review, and continuous verification into a single unified environment engineered for serious software delivery.',
    targetAudience: [
      'Senior Software Engineers',
      'Full-Stack & Systems Architects',
      'AI & Agentic Systems Developers',
      'Technical Leads & Engineering Teams',
    ],
    capabilities: [
      {
        title: 'Multi-Agent Workspace Orchestration',
        description:
          'Spawn and coordinate specialized autonomous agents that research codebases, propose structural edits, run test suites, and execute terminal commands in parallel without blocking main workflows.',
        highlight: 'Parallel Execution',
      },
      {
        title: 'Persistent Project Memory Index',
        description:
          'Maintain real-time structural graphs of your code syntax, AST, Git commit lineage, and past decision logs so agents act with full historical context.',
        highlight: 'Zero Context Loss',
      },
      {
        title: 'Unified Integrated Terminal Engine',
        description:
          'Interact directly with native PTY terminals integrated into agent workflows with full permission controls, command auditing, and background process monitoring.',
        highlight: 'Native Shell Control',
      },
      {
        title: 'Empirical Verification & Traceability',
        description:
          'Every code edit generated by an agent must pass mandatory automated build checks, linter runs, and unit verification before landing in your branch.',
        highlight: 'Verified Code Output',
      },
      {
        title: 'Multi-Window & Multi-Display Canvas',
        description:
          'Detach agents, logs, active terminals, and visual previews across multiple monitors with zero latency or layout thrashing.',
        highlight: 'Workstation Optimized',
      },
      {
        title: 'Local-First Data Isolation',
        description:
          'Your codebase, local git history, and environment secrets remain stored locally on your machine with strict outbound proxy controls.',
        highlight: 'Air-Gapped Ready',
      },
    ],
    platforms: ['Windows', 'macOS', 'Linux'],
    downloads: [
      {
        platform: 'Windows',
        version: 'v0.9.4-preview',
        architecture: 'x64 (64-bit)',
        fileSize: '118 MB',
        releaseDate: '2026-07-15',
        checksumSha256: '9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e',
        minOsVersion: 'Windows 10 / Windows 11 (22H2+)',
        available: true,
        releaseNotesUrl: '/products/paralith#release-notes',
      },
      {
        platform: 'macOS',
        version: 'v0.9.4-preview',
        architecture: 'Apple Silicon (M1/M2/M3/M4) & Intel',
        fileSize: '124 MB',
        releaseDate: '2026-07-15',
        checksumSha256: 'a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0',
        minOsVersion: 'macOS 13.0 (Ventura) or later',
        available: true,
        releaseNotesUrl: '/products/paralith#release-notes',
      },
      {
        platform: 'Linux',
        version: 'v0.9.4-preview',
        architecture: 'x86_64 (.AppImage / .deb)',
        fileSize: '112 MB',
        releaseDate: '2026-07-15',
        checksumSha256: 'f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9',
        minOsVersion: 'Ubuntu 22.04 LTS / Fedora 38+',
        available: true,
        releaseNotesUrl: '/products/paralith#release-notes',
      },
    ],
    heroVisualType: 'paralith-system',
    primaryCtaText: 'Download Paralith Preview',
    secondaryCtaText: 'Request Early Access',
    faqs: [
      {
        question: 'Is Paralith an AI code editor or a complete IDE platform?',
        answer:
          'Paralith is a multi-agent development environment built from the ground up to handle complex, multi-file software engineering tasks rather than simple line-by-line autocompletion. It coordinates workspaces, terminal shells, memory indices, and verification runs.',
      },
      {
        question: 'Does Paralith send my source code to public LLM training datasets?',
        answer:
          'No. Paralith follows strict local-first privacy principles. Code telemetry is completely disabled by default, and project memory indices are stored locally on your device.',
      },
      {
        question: 'Can I use Paralith with custom local models or private LLM endpoints?',
        answer:
          'Yes. Paralith supports local inference via Ollama/vLLM as well as private enterprise cloud endpoints with custom API credentials.',
      },
      {
        question: 'What platforms are currently supported?',
        answer:
          'Paralith builds native desktop distributions for Windows 11/10 (x64), macOS (Universal Binary for Apple Silicon and Intel), and Linux (AppImage & deb).',
      },
    ],
  },
  {
    id: 'pulseboost',
    slug: 'pulseboost',
    name: 'PulseBoost',
    tagline: 'Transparent, evidence-based Windows performance optimization.',
    category: 'System Performance Platform',
    status: 'Available',
    shortDescription:
      'A Windows system performance optimization platform designed around measurable metrics, safety controls, system transparency, and instant rollback.',
    fullDescription:
      'PulseBoost eliminates system latency, unneeded background polling, and memory fragmentation for high-performance software development, compiling, and real-time rendering—without snake-oil registry hacks or dangerous tweaks.',
    targetAudience: [
      'Developers & Build Engineers',
      'Digital Creators & Render Leads',
      'System Administrators',
      'Power Users seeking low latency',
    ],
    capabilities: [
      {
        title: 'Before-and-After Metric Verification',
        description:
          'Measure frame times, CPU thread latency, I/O wait stats, and memory compression efficiency in real-time before and after applying profile tweaks.',
        highlight: 'Empirical Metrics',
      },
      {
        title: 'One-Click Instant Rollback',
        description:
          'Every configuration change creates a hardware-level restore point and delta backup. Revert any setting instantaneously with zero system risk.',
        highlight: '100% Safe',
      },
      {
        title: 'Compiler & Build Accelerator',
        description:
          'Dynamically allocate thread priorities, filesystem cache buffers, and power states specifically during active background build and test scripts.',
        highlight: 'Workload Aware',
      },
      {
        title: 'Telemetry & Bloatware Cleanup',
        description:
          'Safely pause unneeded Windows diagnostic services, background search indexers, and third-party startup hooks while keeping core OS stability intact.',
        highlight: 'Clean OS State',
      },
    ],
    platforms: ['Windows'],
    downloads: [
      {
        platform: 'Windows',
        version: 'v2.1.0-stable',
        architecture: 'x64 (64-bit)',
        fileSize: '24 MB',
        releaseDate: '2026-06-20',
        checksumSha256: '4b3a2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b',
        minOsVersion: 'Windows 10 21H2 or Windows 11',
        available: true,
      },
    ],
    heroVisualType: 'performance-metrics',
    primaryCtaText: 'Download PulseBoost for Windows',
    secondaryCtaText: 'View Optimization Specs',
    faqs: [
      {
        question: 'How is PulseBoost different from generic PC cleaners?',
        answer:
          'Generic cleaners delete temporary files and touch dangerous registry keys. PulseBoost focuses strictly on CPU scheduling latency, background service management, power states, and filesystem I/O caching with full mathematical verification and safe rollback.',
      },
      {
        question: 'Is PulseBoost free to use?',
        answer:
          'PulseBoost offers a comprehensive free tier for individual developers and creators, alongside a professional enterprise license for team deployment.',
      },
    ],
  },
  {
    id: 'tyotrack',
    slug: 'tyotrack',
    name: 'TyoTrack',
    tagline: 'Precision work-time and operations governance platform.',
    category: 'Operations & Enterprise Software',
    status: 'Private Beta',
    shortDescription:
      'A structured operations platform for enterprise teams needing accurate work-time records, multi-company approvals, project allocation, and audit compliance.',
    fullDescription:
      'TyoTrack simplifies operational accountability for multi-entity businesses, consulting firms, and engineering agencies. Track time, manage multi-tier approvals, generate immutable audit reports, and govern access with fine-grained permissions.',
    targetAudience: [
      'Engineering Agencies & Consultancies',
      'Multi-Company Operations Managers',
      'Finance & Compliance Officers',
      'Distributed Team Leads',
    ],
    capabilities: [
      {
        title: 'Multi-Tenant Entity Governance',
        description:
          'Manage complex corporate structures with distinct legal entities, cost centers, approval hierarchies, and localized compliance rules in one portal.',
        highlight: 'Multi-Company Support',
      },
      {
        title: 'Cryptographic Audit Trail',
        description:
          'Time entries, manual adjustments, and manager approvals are recorded in an append-only log preventing unauthorized retrospective editing.',
        highlight: 'Immutable Records',
      },
      {
        title: 'Custom Approval Workflows',
        description:
          'Route project hours through multi-stage approval chains based on client contracts, budget thresholds, and role-based access rules.',
        highlight: 'Flexible Routing',
      },
      {
        title: 'Real-Time Margin & Budget Tracking',
        description:
          'Monitor real-time project profitability, burn rates, and contractor utilization with direct integrations into standard ERP systems.',
        highlight: 'Financial Clarity',
      },
    ],
    platforms: ['Web', 'Cloud', 'Windows', 'macOS'],
    heroVisualType: 'operations-matrix',
    primaryCtaText: 'Request Private Beta Access',
    secondaryCtaText: 'Explore Architecture',
    faqs: [
      {
        question: 'Who is TyoTrack designed for?',
        answer:
          'TyoTrack is built for software consultancies, engineering services firms, and enterprise organizations managing multiple client projects, contractors, and strict billing compliance.',
      },
      {
        question: 'How do I join the Private Beta?',
        answer:
          'Submit a request through our company contact portal specifying your team size and operational requirements.',
      },
    ],
  },
  {
    id: 'launchforge',
    slug: 'launchforge',
    name: 'LaunchForge AI',
    tagline: 'Transform product visions into structured, buildable software specs.',
    category: 'Product & Architecture Engineering',
    status: 'In Development',
    shortDescription:
      'An intelligent workspace for founders, product managers, and engineering leads to convert raw product ideas into complete, buildable engineering blueprints.',
    fullDescription:
      'LaunchForge AI systematically analyzes software requirements, maps component dependencies, generates schema models, designs API interfaces, and creates actionable engineering task graphs.',
    targetAudience: [
      'Product Managers & Technical Founders',
      'Systems Architects & Engineering Leads',
      'R&D Strategy Teams',
    ],
    capabilities: [
      {
        title: 'Automated Software Architecture Mapping',
        description:
          'Generate complete system diagrams, database entity-relationship models, and component interaction graphs from high-level product specifications.',
        highlight: 'Architectural Blueprint',
      },
      {
        title: 'Feature Dependency Graphing',
        description:
          'Identify critical path bottlenecks, tech stack risks, and third-party API dependencies before writing a single line of production code.',
        highlight: 'Risk Elimination',
      },
      {
        title: 'Executable Implementation Plans',
        description:
          'Export structured Markdown implementation plans, OpenAPI schemas, and GitHub issue backlogs formatted for human developers or agentic coding systems.',
        highlight: 'Agent-Ready Backlogs',
      },
    ],
    platforms: ['Web', 'Cloud'],
    heroVisualType: 'workspace-canvas',
    primaryCtaText: 'Join Waitlist',
    secondaryCtaText: 'Read Vision Paper',
    faqs: [
      {
        question: 'When will LaunchForge AI be available?',
        answer:
          'LaunchForge AI is currently in active research and engineering development. We will announce early preview access to waitlisted teams in late 2026.',
      },
    ],
  },
];
